<?php
/**
 * User: elkuku
 * Date: 04.05.12
 * Time: 19:55
 */

class JacliApplicationInterfaceDokuwiki extends JacliApplicationInterface
{
	public function createAdminUser(JacliModelDatabase $db)
	{
		return $this;
	}

	public function createConfig()
	{
		jimport('joomla.filesystem.file');

		$config = $this->config;
		$path = $config->get('targetDir');

		$now = gmdate('r');
		$buffer = <<<EOT
<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: $now
 */

EOT;
		$buffer .= '$conf[\'title\'] = \'' . addslashes($config->get('site_name')) . "';\n";
		$buffer .= '$conf[\'lang\'] = \'' . addslashes($config->get('lang')) . "';\n";
		$buffer .= '$conf[\'license\'] = \'' . addslashes($config->get('license')) . "';\n";

		if ($config->get('useacl'))
		{
			$buffer .= '$conf[\'useacl\'] = 1' . ";\n";
			$buffer .= "\$conf['superuser'] = '@admin';\n";
		}

		if (!file_put_contents($path . '/conf/local.php', $buffer))
			throw new Exception('Unable to write local.php', 1);

		/*
		 * Create admin user
		 */

		if (!$config->get('useacl'))
			return $this;

		// create users.auth.php
		// --- user:MD5password:Real Name:email:groups,comma,seperated
		$output = join(":", array(
			$config->get('admin_user'),
			md5($config->get('admin_password')),
			$config->get('admin_fullname'),
			$config->get('admin_email'),
			'admin,user'
		));

		$buffer = JFile::read($path.'/conf/users.auth.php.dist') . "\n$output\n";

		if (!file_put_contents($path . '/conf/users.auth.php', $buffer))
			throw new Exception('Unable to write users.auth.php', 1);

		// create acl.auth.php
		$buffer = <<<EOT
# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: $now

EOT;
		if ($config->get('policy') == 2)
		{
			$buffer .= "*               @ALL          0\n";
			$buffer .= "*               @user         8\n";
		}
		elseif ($config->get('policy') == 1)
		{
			$buffer .= "*               @ALL          1\n";
			$buffer .= "*               @user         8\n";
		}
		else
		{
			$buffer .= "*               @ALL          8\n";
		}

		if (!file_put_contents($path . '/conf/acl.auth.php', $buffer))
			throw new Exception('Unable to write acl.auth.php', 1);

		return $this;
	}

	public function cleanup()
	{
		return $this;
	}

	public function setupDatabase()
	{
		return $this;
	}

	public function getBrowserLinks()
	{
		return array('Wiki' => '');
	}

	/**
	 * Displays a result message.
	 *
	 * @return array
	 */
	public function getResultMessage()
	{
		// TODO: Implement getResultMessage() method.

		$message = array();

		$message[] = '';
		$message[] = 'Your Dokuwiki has been installed succesfully.';
		$message[] = '';
		$message[] = 'Credentials:';
		$message[] = 'Admin user     : ' . $this->config->get('admin_user');
		$message[] = 'Admin password : ' . $this->config->get('admin_password');
		$message[] = '';

		return $message;
	}
}
